/*
 * Simulates a Hungarian Mode GUI
 */
package gui;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;


/**
 * hungarian mode gui
 * @author Kwnstantinos Perrakis
 * @author Sokratis Athanasiadis
 * @version 1.1
 * Simulates hungarian mode gui
 */
public class Hungarian extends javax.swing.JFrame{

    /**
     * Constructor of the class
     * @param players the number of the players
     */
    public Hungarian(int players) {
        TileStack stack=new TileStack();
        stack.shuffledStuck();
        game=new HungarianMode(stack,players);
        transparent=new Color(0,0,0,0);
        Toolkit t=Toolkit.getDefaultToolkit();
        Dimension d=t.getScreenSize();
        initComponents();
        this.setExtendedState(this.MAXIMIZED_BOTH); 
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        int x=((d.width/2-this.getWidth()/2));
        int y=((d.height/2-this.getHeight()/2));
        this.setLocation(x,y);
        setCursor();
        UpdatePlayersTiles();
        this.setVisible(true);
        if(game.getTurn()!=0){
             multithread thread=new multithread();
             thread.start();
        }
        else {
            JOptionPane.showMessageDialog(this,"It's Your Turn");
        }
    }
    
    
    /**
     * This method sets the coursor of the buttons to hand
     */
    public void setCursor(){
      
        jButton2.setCursor(new Cursor(Cursor.HAND_CURSOR));
        jButton3.setCursor(new Cursor(Cursor.HAND_CURSOR));
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Hungarian");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jButton2.setBackground(transparent);
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/points button.png"))); // NOI18N
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton2MouseEntered(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(transparent);
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/home button.png"))); // NOI18N
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton3MouseEntered(evt);
            }
        });

        jPanel4.setOpaque(false);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Player 1", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(51, 255, 255))); // NOI18N
        jPanel2.setOpaque(false);
        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Table", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 255, 255))); // NOI18N
        jPanel1.setOpaque(false);
        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/table.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(6, 6, 6))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

/**
 * It plays a sound effect when a click is made, and closes this window
 * @param evt mouse clicked
 */
    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
      playSound("Game Menu Click SOUND Effect.wav");
        this.dispose();  // TODO add your handling code here:
    }//GEN-LAST:event_jButton3MouseClicked
/**
 * Appears an info of what this button does when mouse enters the button area
 * @param evt mouse enters the button area
 */
    private void jButton2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseEntered
        jButton2.setToolTipText("show points");
    }//GEN-LAST:event_jButton2MouseEntered
/**
 * Appears an info of what this button does when mouse enters the button area
 * @param evt mouse enters the button area
 */
    private void jButton3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseEntered
       jButton3.setToolTipText("return to menu");
    }//GEN-LAST:event_jButton3MouseEntered
/**
 * Calls the function that plays sound, and appears all players current number of points
 * @param evt mouse clicked
 */
    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        playSound("Game Menu Click SOUND Effect.wav");
        ArrayList<String> temp;
        temp=game.getAllPlayersPoints();
        JOptionPane.showMessageDialog(null,temp);
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed
/**
 * Default close operation
 * @param evt window close
 */
    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        GUi menu=new GUi();
        menu.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    /**
     * It is the listener for the click of a button , also calls the function that plays sounds
     */
     public class Listener implements ActionListener{

        @Override
        public void actionPerformed(ActionEvent e) {
           if (game.getTurn()==0){
           playSound("Click2-Sebastian-759472264.wav");
           playerPlay(Integer.valueOf(Integer.valueOf(e.getActionCommand())));
           }
           if(game.getTurn()!=0){
              multithread thread=new multithread();
              thread.start();
           }
        }
       }
    
    
    
    /**
     * This method makes the move for the player it also calls RoundOver to check if the round is over and checkWinner to check if there is a winner
     * @param i The selected tile
     */
    public void playerPlay(int i){
        if (game.getTurn()==0){
            game.playermoves(i);
            UpdateTableTiles();
            UpdatePlayersTiles();
            }
        boolean flag;
        flag=RoundOver();
        if(flag==true){
           int winner=checkWinner();
                if (winner==-1){             // It means that there is no winner
                    newRound();
                }
                else{
                    return;
                }
        }
    }
  
    
    
  /**
  * This method makes the moves for the Bots it also check if the round is over and if there is a winner 
  * @throws  java.lang.InterruptedException bots play is in a thread
  */  
public void botsPlay() throws InterruptedException{
     while(game.getTurn()!=0&&game.checkPoints()==-1){
            JOptionPane.showMessageDialog(rootPane,"Player "+(game.getTurn()+1)+" play");
            game.botMoves();
            UpdateTableTiles(); 
            boolean flag;
            flag=RoundOver();
            if(flag==true){
                int winner=checkWinner();
                if (winner==-1){             // It means that there is no winner
                    newRound();
                }
                else{
                    return;
                }
            }
            else if (game.getTurn()==0){
                JOptionPane.showMessageDialog(this,"Its your Turn!");
                
            }     
     }
     
     
}
   /**\
    * It checks if there is a winner. If there is one it prints who he is and return to the menu
    * @return -1 if there is no Winner or a number [0,numbofplayers] which is the winner 
    */
    public int checkWinner(){
    int Winner=game.checkPoints();
            if (Winner!=-1){
                if(Winner==0){
                    playSound("Short_triumphal_fanfare-John_Stracke-815794903.wav");
                   JOptionPane.showMessageDialog(null,"You have won"); 
                }
                else {
                    playSound("The Price is Right Losing Horn - Gaming Sound Effect (HD).wav");
                    JOptionPane.showMessageDialog(null,"The winner is Player"+(Winner+1));
                }
                
                this.dispose();
                
            }
            return Winner;
 }
    
    
    /**
     * This method checks if the round is over
     * @return true if a round is over, false else
     */
    public boolean RoundOver(){
              if (game.checkMoves()==false||game.emptyStacks()){
               ArrayList<String> temp;
               game.addPoints();
               temp=game.getAllPlayersPoints();
               JOptionPane.showMessageDialog(null,"The round is Over\n"+temp);
             return true;
              }
         return false;
    }
    
    /**
     * MultiThread for bots moves
     */
    public class multithread extends Thread{
        @Override
        public void run(){
            try {
                botsPlay();
            } catch (InterruptedException ex) {
                Logger.getLogger(Hungarian.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
    
}
    /**
     * This method starts a new Round
     */
    public void newRound(){
        TileStack Stack=new TileStack();
        Stack.shuffledStuck();
        game.newRound(Stack);
        game.startingPlayer();
        if (game.getTurn()==0){
            UpdateTableTiles();
            UpdatePlayersTiles();
            JOptionPane.showMessageDialog(this,"It's Your Turn");
        }
        else {
            UpdateTableTiles();
            UpdatePlayersTiles();
        }
    }
    
    
    /**
     * This method updates the player's tiles panel
     */
    public void UpdatePlayersTiles(){
        int size=game.getPlayers().get(0).GetTilesStack().size();
        PlayersTiles=new ArrayList<>();
        Listener listener=new Listener();
        jPanel2.removeAll();
        for (int i=0;i<size;i++){
            javax.swing.JButton jButton1;
            jButton1 = new javax.swing.JButton();
            jButton1.setSize(new Dimension(30,55));
            jButton1.setOpaque(false);
            jButton1.setBackground(transparent);
            jButton1.setCursor(new Cursor(Cursor.HAND_CURSOR));
            String file=game.getPlayers().get(0).getTile(i).get_side1()+"-"+game.getPlayers().get(0).getTile(i).get_side2()+".png";
            ImageIcon icon=new ImageIcon(file);
            jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/"+icon))); // NOI18N
            jButton1.setActionCommand(String.valueOf(i));
            jButton1.addActionListener(listener);
            PlayersTiles.add(jButton1);
            jPanel2.add(PlayersTiles.get(i));
        }
        jPanel2.revalidate();
        jPanel2.repaint();
        
      }
    
   /**
    * This method Updates the table's panel
    */ 
   public void UpdateTableTiles(){
    TableTiles=new ArrayList<>();
    jPanel1.removeAll();
    int size=game.getTable().size();
    for(int i=0;i<size;i++){
            javax.swing.JLabel jLabel4;
            jLabel4 = new javax.swing.JLabel();
            String file;
            
            if(game.getTable().get(i).get_side1()<=game.getTable().get(i).get_side2()){
             file=game.getTable().get(i).get_side1()+"-"+game.getTable().get(i).get_side2()+".png";
            }
            else{
             file=game.getTable().get(i).get_side1()+"-"+game.getTable().get(i).get_side2()+".png";
            }
            ImageIcon icon=new ImageIcon(file);
            jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/"+icon))); // NOI18N
            jLabel4.setSize(new Dimension(30,55));
            TableTiles.add(jLabel4);
            jPanel1.add(TableTiles.get(i));
    }
    jPanel1.revalidate();
    jPanel1.repaint();
}
   
   /**
     * This function starts all the sound effects of this menu
     * @param soundName the file that contains the sound that we want to play
     */
   public void playSound(String soundName)
 {
   try 
   {
   AudioInputStream audioInputStream = AudioSystem.getAudioInputStream(new File(soundName).getAbsoluteFile( ));
   Clip clip = AudioSystem.getClip( );
   clip.open(audioInputStream);
   clip.start( );
   }
   catch(Exception ex)
   {
     System.out.println("Error with playing sound.");
     ex.printStackTrace( );
   }
 }

    private ArrayList<JButton> PlayersTiles;
    private ArrayList<JLabel> TableTiles;
    private final HungarianMode game;
    private final Color transparent;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}


